### ISSUE TITLE
wire @faffa

### ISSUE THREAD

**Issue by faffa42** [fuckpiracyshield/data#2]
sudo

**Comment by fuckpiracyshield** [comment]
> sudo

mettiti su qualcosa di più leggero? non so che dirti... sinceramente fa anche un po' freddo eh

**Comment by faffa42** [comment]
Speravo più che altro che volessi fare una chiacchierata riservata. Eventualmente anche qui 5v55oognh2w6ynry43keq7igvvvl27gu4luv6ofjmnfuw46o7s6fmpqd.onion

**Comment by fuckpiracyshield** [comment]
Va bene, certo! ;-)
